;; DO NOT EDIT! This file is automatically generated from C headers to expose structures to assembly.
;; See /kernel/expose_structs.c to see all structs exposed.

struc Thread
    .class_list resb 16
    .gap16 resb 32 ; rsvd
    .s_class resd 1
    .priority resd 1
endstruc
