/* utility to expose C structs to assembly by automatically generating assembly files. */
/* to add a new struct, create a copy of one of the EXPOSE_*_STRUCT macros and make
 * it copy each member. I'm not sure if there's a way to do this with less repetition
 * but I couldn't think of one. */

#include <stdio.h>
#include <assert.h>
#include <unistd.h>
#include <stdint.h>

/* for stuff to expose (yeah yeah relative paths, whatever) */
#include <scheduler.h>

#define OUTPUT "src/isa/x86_64/exposed_structs.asm"

bool file_exists(char *fname) {
    return !access(fname, F_OK);
}

const char *output_header = ";; DO NOT EDIT! This file is automatically generated"
                            " from C headers to expose structures to assembly.\n;; See "
                            "/kernel/expose_structs.c to see all structs exposed.\n\n";

const char *size_strs[] = {
    [1] = "resb",
    [2] = "resw",
    [4] = "resd",
    [8] = "resq",
};

int round_up(int num, int multiple) {
    if (multiple == 0)
        return num;

    int remainder = num % multiple;
    if (remainder == 0)
        return num;

    return num + multiple - remainder;
}
#define SIZE_STR(val) (assert(sizeof(val) <= 8), size_strs[sizeof(val)])

// expose a single struct member. must be a SINGLE ELEMENT of size 1/2/4/8, nothing larger.
#define EXPOSE_STRUCT_MEMBER(file, bytes_done, type, member) \
    do { \
        if (bytes_done < offsetof(type, member)) { \
            fprintf(file, "    .gap%zu resb %zu ; rsvd\n", bytes_done, offsetof(type,member)-bytes_done); \
            bytes_done += offsetof(type,member)-bytes_done; \
        } \
        type get_from; \
        fprintf(file, "    ." #member " "); \
        if (sizeof(get_from.member) <= 8) { \
            fprintf(file, SIZE_STR(get_from.member)); \
            fprintf(file, " 1\n"); \
        } else { \
            fprintf(file, "resb %zu\n", sizeof(get_from.member)); \
        } \
        bytes_done += sizeof(get_from.member); \
    } while (0)


#define EXPOSE_THREAD_STRUCT(file, type) \
    do { \
        fprintf(file, "struc " #type "\n"); \
        size_t bytes_done = 0; \
        size_t struct_size = sizeof(type); \
        EXPOSE_STRUCT_MEMBER(file, bytes_done, type, class_list); \
        EXPOSE_STRUCT_MEMBER(file, bytes_done, type, s_class); \
        EXPOSE_STRUCT_MEMBER(file, bytes_done, type, priority); \
        \
        fprintf(file, "endstruc\n"); \
    } while (0)

int main(void) {
    if (file_exists(OUTPUT) && remove(OUTPUT) < 0) {
        fprintf(stderr, OUTPUT " already exists but it could not be removed, maybe try as superuser\n");
        return -1;
    }

    FILE *f = fopen(OUTPUT, "w");
    if (!f) {
        fprintf(stderr, "failed to create " OUTPUT);
        return -1;
    }

    fprintf(f, output_header);
    EXPOSE_THREAD_STRUCT(f, Thread);
    
    fclose(f);
}
